PKU-180
Sage-Bionetworks/Biomarin-PKU-iOS pull request #59
Opened 2021-02-12 02:56 UTC by dephillipsmichael

From the aftermath of some user's having their ScheduledActivities re-created, I added an extra layer of protection when calculating study start date.  The study start date is now a more in-depth calculation that will always return the oldest scheduledOn date, which will be the true study start date.

A unit test has been added to explicitly test this scenario, and it is running successfully now after the code change.

2021-02-12 14:59 UTC, DanWebster requested changes

2021-02-12 14:59 UTC, DanWebster commented on BiomarinPKU/BiomarinPKUStudyTests/ActivityScheduleManagerTests.swift
> +        "RestingKineticTremor",
@dephillipsmichael RestingKineticTremor is listed twice here.  This probably doesn't have a significant effect, but just in case we should remove duplicates

2021-02-12 14:59 UTC, DanWebster commented on BiomarinPKU/BiomarinPKUStudyTests/ActivityScheduleManagerTests.swift
> +        "RestingKineticTremor",
```suggestion
        
```

2021-02-12 14:59 UTC, DanWebster commented on BiomarinPKU/BiomarinPKUStudyTests/ActivityScheduleManagerTests.swift
> +        "RestingKineticTremor",
I put an inline suggestion/commit, but I wouldn't trust this because I can't tell from the github UI what the functional  effect will be on the list (whether we are leaving two commas, empty newline, etc.

2021-02-12 17:08 UTC, dephillipsmichael commented on BiomarinPKU/BiomarinPKUStudyTests/ActivityScheduleManagerTests.swift
> +        "RestingKineticTremor",
I went ahead and removed the duplicate RestingKineticTremor on my device.  It had no effect on the algorithm or tests except that it wasn't a true set of the ScheduledActivities on bridge for the study app.

2021-02-12 20:51 UTC, DanWebster approved these changes

2021-02-12 20:51 UTC, DanWebster commented
@dephillipsmichael Going to leave this PR open for now, pending results of the server-side fix

2021-03-12 17:33 UTC, dephillipsmichael commented
Closing, put leaving branch open in case we need this down the road.

2021-03-12 17:33 UTC, closed without merging